name: derta
version: 0.0.0

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  json_annotation: ^2.2.0

dev_dependencies:
  path: ^1.6.2
  yaml: ^2.1.15
  build_runner: ^1.3.5
  json_serializable: ^2.2.2
  test: ^1.6.2
